apiVersion: qserv.lsst.org/v1beta1
kind: Qserv
metadata:
  name: qserv
spec:
  czar:
    image: qserv/lite-qserv:2021.10.1-rc1-105-gd2b80a603
    dbImage: qserv/lite-mariadb:2021.10.1-lite-rc2
  ingest:
    dbImage: qserv/lite-mariadb:2021.10.1-lite-rc2
  replication:
    image: qserv/lite-qserv:2021.10.1-rc1-105-gd2b80a603
    dbImage: qserv/lite-mariadb:2021.10.1-lite-rc2
  worker:
    image: qserv/lite-qserv:2021.10.1-rc1-105-gd2b80a603
    dbImage: qserv/lite-mariadb:2021.10.1-lite-rc2
  xrootd:
    image: qserv/lite-qserv:2021.10.1-rc1-105-gd2b80a603
