apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  czar:
    image: qserv/qserv:deps_20210426_1747
  dashboard:
    image: qserv/dashboard:2021.04.0
  worker:
    image: qserv/qserv:deps_20210426_1747
  replication:
      image: qserv/qserv:deps_20210426_1747
  xrootd:
    image: qserv/qserv:deps_20210426_1747
