// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/lsst/qserv-operator/pkg/apis/qserv/v1alpha1.Qserv":       schema_pkg_apis_qserv_v1alpha1_Qserv(ref),
		"github.com/lsst/qserv-operator/pkg/apis/qserv/v1alpha1.QservSpec":   schema_pkg_apis_qserv_v1alpha1_QservSpec(ref),
		"github.com/lsst/qserv-operator/pkg/apis/qserv/v1alpha1.QservStatus": schema_pkg_apis_qserv_v1alpha1_QservStatus(ref),
	}
}

func schema_pkg_apis_qserv_v1alpha1_Qserv(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "Qserv is the Schema for the qservs API",
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lsst/qserv-operator/pkg/apis/qserv/v1alpha1.QservSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/lsst/qserv-operator/pkg/apis/qserv/v1alpha1.QservStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/lsst/qserv-operator/pkg/apis/qserv/v1alpha1.QservSpec", "github.com/lsst/qserv-operator/pkg/apis/qserv/v1alpha1.QservStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_qserv_v1alpha1_QservSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "QservSpec defines the desired state of Qserv",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}

func schema_pkg_apis_qserv_v1alpha1_QservStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "QservStatus defines the observed state of Qserv",
				Properties:  map[string]spec.Schema{},
			},
		},
		Dependencies: []string{},
	}
}
