kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: czar
provisioner: pd.csi.storage.gke.io 
parameters:
  type: pd-ssd
allowVolumeExpansion: true
reclaimPolicy: Retain 
volumeBindingMode: WaitForFirstConsumer
