kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: qserv
provisioner: pd.csi.storage.gke.io 
parameters:
  type: pd-balanced
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
