apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  storageClassName: "qserv"
  storage: "100Gi"
  czar:
    storageClassName: "czar"
    storage: "500Gi"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tier
              operator: In
              values:
              - czar
    proxyresources:
      requests:
        cpu: 24
  queryService:
      annotations:
        cloud.google.com/load-balancer-type: Internal
      loadBalancerIP: 10.134.1.211
      type: LoadBalancer
  worker:
    storage: "2Ti"
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tier
              operator: In
              values:
              - worker
    replicas: 5
    replicationresources:
      limits:
        cpu: 14
