# permissions for end users to view qservs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qserv-viewer-role
rules:
- apiGroups:
  - qserv.lsst.org
  resources:
  - qservs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - qserv.lsst.org
  resources:
  - qservs/status
  verbs:
  - get
