apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: qservs.qserv.lsst.org
spec:
  group: qserv.lsst.org
  names:
    kind: Qserv
    listKind: QservList
    plural: qservs
    singular: qserv
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Qserv is the Schema for the qservs API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: QservSpec defines the desired state of Qserv
          properties:
            czar:
              description: Czar defines the settings for czar cluster
              properties:
                image:
                  type: string
                replicas:
                  format: int32
                  type: integer
              type: object
            redis:
              description: Redis defines the settings for redis cluster
              properties:
                master:
                  format: int32
                  type: integer
                replicas:
                  format: int32
                  type: integer
                version:
                  type: string
              type: object
            replication:
              description: Replication defines the settings for the replication framework
              properties:
                dbimage:
                  type: string
                image:
                  type: string
              type: object
            storagecapacity:
              type: string
            storageclass:
              description: Common settings
              type: string
            tolerations:
              description: Tolerations defines the settings for adding custom tolerations
                to all pods
              items:
                description: The pod this Toleration is attached to tolerates any
                  taint that matches the triple <key,value,effect> using the matching
                  operator <operator>.
                properties:
                  effect:
                    description: Effect indicates the taint effect to match. Empty
                      means match all taint effects. When specified, allowed values
                      are NoSchedule, PreferNoSchedule and NoExecute.
                    type: string
                  key:
                    description: Key is the taint key that the toleration applies
                      to. Empty means match all taint keys. If the key is empty, operator
                      must be Exists; this combination means to match all values and
                      all keys.
                    type: string
                  operator:
                    description: Operator represents a key's relationship to the value.
                      Valid operators are Exists and Equal. Defaults to Equal. Exists
                      is equivalent to wildcard for value, so that a pod can tolerate
                      all taints of a particular category.
                    type: string
                  tolerationSeconds:
                    description: TolerationSeconds represents the period of time the
                      toleration (which must be of effect NoExecute, otherwise this
                      field is ignored) tolerates the taint. By default, it is not
                      set, which means tolerate the taint forever (do not evict).
                      Zero and negative values will be treated as 0 (evict immediately)
                      by the system.
                    format: int64
                    type: integer
                  value:
                    description: Value is the taint value the toleration matches to.
                      If the operator is Exists, the value should be empty, otherwise
                      just a regular string.
                    type: string
                type: object
              type: array
            worker:
              description: Worker defines the settings for worker cluster
              properties:
                image:
                  type: string
                replicas:
                  format: int32
                  type: integer
              type: object
            xrootd:
              description: Xrootd defines the settings for worker cluster
              properties:
                image:
                  type: string
                replicas:
                  format: int32
                  type: integer
              type: object
          type: object
        status:
          description: QservStatus defines the observed state of Qserv
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
