apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: qserv
    instance: qserv
    pvc_name: qserv-data-qserv-ingest-db-0
  name: pv-qserv-data-qserv-ingest-db-0
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 100Gi
  local:
    path: /data/qserv-qserv/ingest
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - ccqserv202
  persistentVolumeReclaimPolicy: Retain
  storageClassName: qserv-local-storage
  volumeMode: Filesystem
