apiVersion: qserv.lsst.org/v1beta1
kind: Qserv
metadata:
  name: example-qserv
spec:
  czar:
    image: qserv/lite-qserv:
    replicas: 1
  imagePullPolicy: IfNotPresent
  ingest:
    dbImage: qserv/lite-mariadb:
  replication:
    dbImage: qserv/lite-mariadb:
    image: qserv/lite-qserv:
  storage: 1Gi
  storageClassName: standard
  worker:
    image: qserv/lite-qserv:
    replicas: 2
  xrootd:
    image: qserv/lite-qserv:
    replicas: 2
