apiVersion: qserv.lsst.org/v1beta1
kind: Qserv
metadata:
  name: example-qserv
spec:
  czar:
    image: qserv/lite-qserv:2022.6.1-rc1
    replicas: 1
  imagePullPolicy: IfNotPresent
  ingest:
    dbImage: qserv/lite-mariadb:2022.6.1-rc1
  replication:
    dbImage: qserv/lite-mariadb:2022.6.1-rc1
    image: qserv/lite-qserv:2022.6.1-rc1
  storage: 1Gi
  storageClassName: standard
  worker:
    image: qserv/lite-qserv:2022.6.1-rc1
    replicas: 2
  xrootd:
    image: qserv/lite-qserv:2022.6.1-rc1
    replicas: 2
