apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: <PVC_NAME>
    labels:
        app: qserv
spec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Filesystem
    resources:
        requests:
            storage: 100Gi # Mandatory, must be the same in PV
    storageClassName: qserv-local-storage
    selector:
        matchLabels:
            pvc_name: <DATA_ID>
