apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  storage: "100Gi"
  czar:
    storage: "500Gi"
  queryService:
      loadBalancerIP: 10.140.1.211
  worker:
    storage: "2Ti"
    replicas: 5
