apiVersion: qserv.lsst.org/v1alpha1
kind: Qserv
metadata:
  name: qserv
spec:
  storage: "100Gi"
  czar:
    storage: "500Gi"
  queryService:
      annotations:
        cloud.google.com/load-balancer-type: Internal
      type: LoadBalancer
      loadBalancerIP: 10.136.1.211
  worker:
    storage: "2Ti"
    replicas: 5
