apiVersion: qserv.lsst.org/v1beta1
kind: Qserv
metadata:
  name: qserv
spec:
  storage: "100Gi"
  czar:
    storage: "4Ti"
  queryService:
      annotations:
        cloud.google.com/load-balancer-type: Internal
      type: LoadBalancer
      loadBalancerIP: 10.136.1.211
  worker:
    storage: "10Ti"
    replicas: 5
  ingest:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tier
              operator: In
              values:
              - 'utility'
  xrootd:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: tier
              operator: In
              values:
              - 'utility'

