apiVersion: qserv.lsst.org/v1beta1
kind: Qserv
metadata:
  name: qserv
spec:
  storageClassName: "qserv-local-storage"
  storage: "100Gi"
  worker:
    replicas: 30
  tolerations:
  - key: "dedicated"
    operator: "Equal"
    value: "qserv"
    effect: "NoSchedule"
